# Generated by Django 4.2.3 on 2023-07-10 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbox_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('option_a_label', models.CharField(max_length=200)),
                ('option_a_votes', models.PositiveIntegerField(default=0)),
                ('option_b_label', models.CharField(max_length=200)),
                ('option_b_votes', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b')], max_length=1, null=True)),
                ('voting_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10)),
                ('duration_minutes', models.IntegerField()),
                ('chatbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatbox')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.chatbox')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
