# Generated by Django 4.2.3 on 2023-07-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='chatbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.chatbox'),
        ),
    ]
