# Generated by Django 4.2.3 on 2023-07-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_alter_comment_creator_alter_poll_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_member_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_member_permission_set', to='auth.permission'),
        ),
    ]
