# Generated by Django 4.2.3 on 2023-07-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_groups_alter_member_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'user', 'verbose_name_plural': 'members'},
        ),
    ]
